### ISSUE TITLE
建议：搜索后没有返回按钮

### ISSUE THREAD

**Issue by eallion** [soulteary/docker-flare#10]
搜索后没有返回按钮。

**Comment by soulteary** [comment]
感谢反馈，暂时在这里更新了一个提示文本，点击文本可以返回，或者再敲一次回车。 @eallion 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/1500781/154616594-c64bf994-91ea-424d-80c1-e7692d7dc658.png">
