### ISSUE TITLE
主页图标恒为大写字母

### ISSUE THREAD

**Issue by TerminalReed** [soulteary/docker-flare#108]
### 你遇到了什么样的麻烦？

配置表中配置的书签名称配置了包括大小写的英文单词，但首页全部显示为大写字母
![image](https://user-images.githubusercontent.com/30360824/224333845-a79d0793-12d3-408e-a5e9-d97fa6a1fbb3.png)
![image](https://user-images.githubusercontent.com/30360824/224333719-91a829ec-d25f-4bc1-8506-a32b3f6b61b3.png)

### 如何复现这个问题？

我看到#31中提到在0.3.3版本这个问题并修复了，但我在最新版本的配置中依然出现了这个情况

### 应用版本

程序版本：0.4.0 / 9d209e38a3bc7637e14e0762efc7e4bc8f39d03e
威联通docker镜像

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by TerminalReed** [comment]
重新拉取了0.3.3 / fe6d1f4版本的docker镜像这个问题依然存在，想问下是我哪里配置的错误吗？感谢开发者！
![image](https://user-images.githubusercontent.com/30360824/224335893-c333e3d8-4ba1-4871-851b-49b4faa1fcf8.png)
![image](https://user-images.githubusercontent.com/30360824/224335937-3d438154-d3b2-4535-85a2-120922977a16.png)

**Comment by LightAPIs** [comment]
将 `/settings/appearance` 中的"保持配置和界面链接大小写一致"设置为"是"保存；或者直接编辑 `config.yml` 将 `KeepLetterCase` 设为 `true`。

**Comment by TerminalReed** [comment]
> 将 `/settings/appearance` 中的"保持配置和界面链接大小写一致"设置为"是"保存；或者直接编辑 `config.yml` 将 `KeepLetterCase` 设为 `true`。

感谢！成功解决。设置的时候没理解该选项的意思。感谢您的帮助
