### ISSUE TITLE
没事了，我的问题

### ISSUE THREAD

**Issue by xiaobaixuejava** [soulteary/docker-flare#112]
### 你遇到了什么样的麻烦？

我在nginx 配置的有后缀地址， 通过ip:端口/xxx 登录，但是通过你这个导航点击后端口变为了80,也就是变为 ip/xxx,希望能修改下逻辑 谢谢

### 如何复现这个问题？

你可以试试看

### 应用版本

0.4

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by Youwenqwq** [comment]
建议Close一下这个Issue~
