### ISSUE TITLE
能否集成一个密码保存功能

### ISSUE THREAD

**Issue by shoreson** [soulteary/docker-flare#118]
### 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？

网页收集+账号密码同步保存，这样更方便一点，不同设备使用更方便

### 请描述你想要得到的结果

密码同步，类似于1pass或者bitwarden

### 请描述你想要的替代方案

无

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by thelittlefox** [comment]
密码同步交给专业的软件去做吧docker部署一个Vaultwarden。
密码不止涉及到同步保存，还有自动填充应该也是刚需。Vaultwarden在PC浏览器，iOS上都有比较成熟的解决方案。
