### ISSUE TITLE
部分网址转换不了

### ISSUE THREAD

**Issue by sungamma** [soulteary/docker-flare#119]
### 你遇到了什么样的麻烦？

这类网址貌似redir不了
https://aaa.bbssssssssb.gg:9443/?launchApp=SYNO.SDS.Drive.Application
直接输入类似上述网址可以访问，但在flare里面，由于有个转换的过程，发现不了解析出该地址，从而访问不了

### 如何复现这个问题？

解析下这个地址
https://aaa.bbssssssssb.gg:9443/?launchApp=SYNO.SDS.Drive.Application

直接报错
找不到 xxxx.xxx.xxxx 的网页找不到与以下网址对应的网页：https://xxxx.xxx.xxxx/redir/xxxxxM6Ly9hYWEuYmJzc3Nzc3Nzc2IudGs6OTQ0My8/bGF1bmNoQXBwPVNZTk8uU0RTLkRyaXZlLkFwcGxpY2F0aW9u

### 应用版本

项目地址：[soulteary/docker-flare](https://github.com/soulteary/docker-flare)

程序版本：0.4.0 / 9d209e38a3bc7637e14e0762efc7e4bc8f39d03e

构建时间：2022-09-17T12:42:33Z

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by sungamma** [comment]
你看下[LightAPIs](https://github.com/LightAPIs)他的仓库，里面有改过的docker镜像。解决了这个问题

> 我也遇到了同样的问题我一共有1400多个书签其中就有部分书签没有转换成功，具体是哪些我没有一一去试具体哪些书签无法识别，因为书签数量实在是太多了，我之前以为是书签数量超过上限了，但我将正确可以识别的链接复制了一千份测试了一下，发现并不是书签突破上限的问题，程序版本：v0.4.1 - 2023.05.07，烦请修复一下谢谢。

**Comment by catbor** [comment]
> 你看下[LightAPIs](https://github.com/LightAPIs)他的仓库，里面有改过的docker镜像。解决了这个问题 https://github.com/LightAPIs/flaring
> 
> > 我也遇到了同样的问题我一共有1400多个书签其中就有部分书签没有转换成功，具体是哪些我没有一一去试具体哪些书签无法识别，因为书签数量实在是太多了，我之前以为是书签数量超过上限了，但我将正确可以识别的链接复制了一千份测试了一下，发现并不是书签突破上限的问题，程序版本：v0.4.1 - 2023.05.07，烦请修复一下谢谢。

是的，我目前暂时切换到了这个镜像，他的那个书签排版布局和分类也做了更改我很喜欢，期待后续作者能够将他的这部分改动和浏览器书签和flare书签格式互转导入功能加入，期待下个版本的更新。
