### ISSUE TITLE
通过Nginx反向代理之后，获取资源都报错了

### ISSUE THREAD

**Issue by firekula** [soulteary/docker-flare#123]
### 你遇到了什么样的麻烦？

家庭网站通过反向代理设置首页之后，加载资源出现了问题，子页面也无法访问
http://firekula.site/

### 如何复现这个问题？

![image](https://github.com/soulteary/docker-flare/assets/44957428/5d8cf23f-58b6-4718-a6df-000115053ff3)
![image](https://github.com/soulteary/docker-flare/assets/44957428/5fad2029-b587-4dba-8b1c-ac1f5cb78860)
![image](https://github.com/soulteary/docker-flare/assets/44957428/c9d523f1-859a-4885-a3d5-2442956db3f8)

### 应用版本

![image](https://github.com/soulteary/docker-flare/assets/44957428/95712488-f615-4360-8d43-47022354af47)

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by LightAPIs** [comment]
我觉得问题有可能是出在 `try_files` 指令上，你是本地上还有其他文件需要访问吗？或许你也可以尝试类似下面这样的配置：

```nginxconf
server {
    location / {
        try_files $uri @proxy;
    }

    location @proxy {
        proxy_pass http://192.168.3.57:5005;
    }
}
```

**Comment by firekula** [comment]
这样写就可以了！谢谢你！
