### ISSUE TITLE
[Flare 应用] 内名称强制大写

### ISSUE THREAD

**Issue by thedavidweng** [soulteary/docker-flare#127]
### 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？

填写在 [Flare 应用] 的内名称会强制全部大写显示，我觉得不太合理，尤其当应用名不是中文而是英文时，例如 qBittorrent 会显示成 QBITTORRENT，很不方便识别。

### 请描述你想要得到的结果

根据我填写的内容来呈现

### 请描述你想要的替代方案

加一个【强制大写】开关或者直接取消这个 Feature

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by LightAPIs** [comment]
打开 `/settings/appearance` 将"保持配置和界面链接大小写一致"设为"是"即可。

**Comment by thedavidweng** [comment]
> 

感谢

**Comment by thedavidweng** [comment]
> 打开 `/settings/appearance` 将"保持配置和界面链接大小写一致"设为"是"即可。

感谢
