### ISSUE TITLE
能否使用动态url

### ISSUE THREAD

**Issue by ztzheng** [soulteary/docker-flare#136]
### 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？

我在家访问nextcloud地址是http://192.168.1.1/nextcloud，当我在其他网络环境中，访问的地址可能变成http://10.0.1.1/nextcloud

### 请描述你想要得到的结果

1、[flare]:http://192.168.1.1:5005 [nextcloud]:http://192.168.1.1/nextcloud
2、[flare]:http://10.0.1.1:5005 [nextcloud]:http://10.0.1.1/nextcloud

### 请描述你想要的替代方案

支持域名参数

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by LightAPIs** [comment]
😝 看起来和 #129 的需求是一样的。
