### ISSUE TITLE
希望在日志输出里对登陆失败的行为返回401错误

### ISSUE THREAD

**Issue by CyanWoods** [soulteary/docker-flare#137]
### 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？

昨天测试fail2ban的时候发现登陆失败的时候依然是200状态码，因此没法筛选出来异常的登陆行为

### 请描述你想要得到的结果

希望在日志输出里对登陆失败的行为返回401

### 请描述你想要的替代方案

希望在日志输出里对登陆失败的行为返回401错误

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by LightAPIs** [comment]
🤨 奇怪了，当前程序里登录失败时响应的状态码是 `400` 呀，难道在 fail2ban 中看到的会不一样？还是说你的描述只是打错了，其实是想规范一些将 `400` 改成 `401`。

**Comment by CyanWoods** [comment]
不好意思，应该是我看错了，登陆失败的状态码确实是400。
