### ISSUE TITLE
建议：图标支持图片外链显示

### ISSUE THREAD

**Issue by lmm214** [soulteary/docker-flare#14]
或者默认空则使用 

http://favicon.yandex.net/favicon/google.com/

的 favicon 接口

**Comment by lmm214** [comment]
/resources/mdi-cheat-sheets/ 图标默认的这个路径有点长……

**Comment by soulteary** [comment]
感谢反馈 @lmm214 ，依次来回复这两个问题：

第一个问题，是能否使用外链图片，好像确实是应该支持一下，之前只考虑了性能表现、内容安全（CSP），以及风格统一。
第二个问题，我在做在线编辑功能，这个地址确实是又丑又长，我想想怎么干掉它。

第一个问题中的功能需要晚一些，代码调整和待处理的细碎事项蛮多的，第二个问题，应该下一个小版本能解决。

**Comment by lmm214** [comment]
嗯嗯，已切换为 flare ，flame 的前端编辑虽然方便，但 node 的实时渲染还是会在打开一刹那闪烁。

**Comment by eallion** [comment]
`https://www.google.cn/s2/favicons?domain_url=example.com`

**Comment by soulteary** [comment]
考虑隐私优先，或许这个功能可以内置，看了下实现成本不高。

不过为了实现更简单，也可以先选择使用 yandex、google.cn 来获取。

**Comment by soulteary** [comment]
v0.3.1 版本开始支持外链，和对没有填写图标的项目，自动获取站点 favicon。

如果需要自动获取，需要在后台打开下面的配置，选择自动获取。 @lmm214 @eallion 

![image](https://user-images.githubusercontent.com/1500781/155254979-bf3e27d1-8f27-4ff5-9f28-5af466896efd.png)

**Comment by eallion** [comment]
Yandex  API 的问题在于，如果一个网站本身没有设置 favicon.ico 则返回空白，Google API 却会返回一个地球图标。对网站样式设计来说 Google API 更优。

**Comment by soulteary** [comment]
> Yandex API 的问题在于，如果一个网站本身没有设置 favicon.ico 则返回空白，Google API 却会返回一个地球图标。对网站样式设计来说 Google API 更优。

是的，或许直接开放存储接口，让用户自己来玩更好，比如用户能自己定义图片、favicon（减少外链还能进一步带来性能提升）。
