### ISSUE TITLE
建议增加备份或恢复功能，设置好后备份恢复功能可以转换服务器。

### ISSUE THREAD

**Issue by cclove845** [soulteary/docker-flare#141]
### 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？

建议增加备份或恢复功能，设置好后备份恢复功能可以转换服务器。

### 请描述你想要得到的结果

备份恢复功能可以转换服务器

### 请描述你想要的替代方案

建议增加备份或恢复功能

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by LightAPIs** [comment]
duplicate: #122

**Comment by lioooooh** [comment]
可以考虑使用  Duplicati   做备份，

备份不一定是flare的强项，而且即使做了也只能备份到本机，但风险往往都是本机出故障。

所以使用Duplicati做异地，或者备份到其他服务器是非常好的选择
