### ISSUE TITLE
自定义页脚的数据某些只对后台起作用，但是主界面不起作用。

### ISSUE THREAD

**Issue by wanrenbuwanxin** [soulteary/docker-flare#154]
### 你遇到了什么样的麻烦？

自定义页脚的数据某些只对后台起作用，但是主界面不起作用。比如调用一言的数据，后台刷新一次就会变化一次，但是主界面不会变动。
![后台](https://github.com/soulteary/docker-flare/assets/27992177/6963a474-3bea-4272-8242-fae73ed5c8c9)
![Uploading 首页.png…]()

### 如何复现这个问题？

     下面这个是使用的代码

 <br />
        <center class="dibu">
            <div style=" line-height: 20px;font-size: 9pt;font-weight: bold;">
                <span>
                    "
                    <span style="color: rgb(13, 109, 252); font-weight: bold;" id="hitokoto">
                        <a href="#" id="hitokoto_text">
                            “纵使结局不如意，遇见已是上上签”，其实有些人，光是遇见，就已经很幸运了…
                        </a>
                    </span> "
                </span>
                <p style="margin-left: 10rem;font-size: 8pt;">
                    <small>
                        —— Anwen's Cloud
                    </small>
                </p>
            </div>

                    </a>
                </span>
                <span class="nav-item">
                    <a class="nav-link" href="https://flare.wscsmile.cn:8888/" target="_blank">
                        <i class="fas fa-edit" style="color:#409EFF" aria-hidden="true">
                        </i>
                        主页 |
                    </a>
                </span>
                <span class="nav-item">
                    <a class="nav-link" href="http://wscsmile.cn:8090/" target="_blank">
                        <i class="fas fa-edit" style="color:#409EFF" aria-hidden="true">
                        </i>
                        博客 |
                    </a>
                </span>
                <span class="nav-item">
                    <a class="nav-link" href="http://wscsmile.cn:8090/message" target="_blank">
                        <i class="fas fa-comment-lines" style="color:#409EFF;" aria-hidden="true">
                        </i>
                        留言 |
                    </a>
                </span>
                
                <span class="nav-item">
                    <a class="nav-link" href="/@manage" target="_blank">
                        <i class="fa-solid fa-folder-gear" style="color:#409EFF;" aria-hidden="true">
                        </i>
                        管理 
    
    <script src="https://v1.hitokoto.cn/?encode=js&select=%23hitokoto" defer></script>

<script type="text/javascript">
         ! function (e, t, a) {
            function r() {
                for (var e = 0; e < s.length; e++) s[e].alpha <= 0 ? (t.body.removeChild(s[e].el), s.splice(e, 1)) : (s[
                        e].y--, s[e].scale += .004, s[e].alpha -= .013, s[e].el.style.cssText = "left:" + s[e].x +
                    "px;top:" + s[e].y + "px;opacity:" + s[e].alpha + ";transform:scale(" + s[e].scale + "," + s[e]
                    .scale + ") rotate(45deg);background:" + s[e].color + ";z-index:99999");
                requestAnimationFrame(r)
            }
            function n() {
                var t = "function" == typeof e.onclick && e.onclick;
                e.onclick = function (e) {
                    t && t(), o(e)
                }
            }
 
            function o(e) {
                var a = t.createElement("div");
                a.className = "heart", s.push({
                    el: a,
                    x: e.clientX - 5,
                    y: e.clientY - 5,
                    scale: 1,
                    alpha: 1,
                    color: c()
                }), t.body.appendChild(a)
            }
 
            function i(e) {
                var a = t.createElement("style");
                a.type = "text/css";
                try {
                    a.appendChild(t.createTextNode(e))
                } catch (t) {
                    a.styleSheet.cssText = e
                }
                t.getElementsByTagName("head")[0].appendChild(a)
            }
 
            function c() {
                return "rgb(" + ~~(255 * Math.random()) + "," + ~~(255 * Math.random()) + "," + ~~(255 * Math
                    .random()) + ")"
            }
            var s = [];
            e.requestAnimationFrame = e.requestAnimationFrame || e.webkitRequestAnimationFrame || e
                .mozRequestAnimationFrame || e.oRequestAnimationFrame || e.msRequestAnimationFrame || function (e) {
                    setTimeout(e, 1e3 / 60)
                }, i(
                    ".heart{width: 10px;height: 10px;position: fixed;background: #f00;transform: rotate(45deg);-webkit-transform: rotate(45deg);-moz-transform: rotate(45deg);}.heart:after,.heart:before{content: '';width: inherit;height: inherit;background: inherit;border-radius: 50%;-webkit-border-radius: 50%;-moz-border-radius: 50%;position: fixed;}.heart:after{top: -5px;}.heart:before{left: -5px;}"
                ), n(), r()
        }(window, document);
    
</script>

### 应用版本

最新版本。

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by LightAPIs** [comment]
🤨 因为你贴的示例代码格式乱了，所以我这边大概按照以下页脚内容测试了下：

```html
<a id="hitokoto"></a>
<br />
</span>
<span class="nav-item">
  <a class="nav-link" href="https://flare.wscsmile.cn:8888/" target="_blank">
    <i class="fas fa-edit" style="color:#409EFF" aria-hidden="true">
    </i>
    主页 |
  </a>
</span>
<span class="nav-item">
  <a class="nav-link" href="http://wscsmile.cn:8090/" target="_blank">
    <i class="fas fa-edit" style="color:#409EFF" aria-hidden="true">
    </i>
    博客 |
  </a>
</span>
<span class="nav-item">
  <a class="nav-link" href="http://wscsmile.cn:8090/message" target="_blank">
    <i class="fas fa-comment-lines" style="color:#409EFF;" aria-hidden="true">
    </i>
    留言 |
  </a>
</span>
<!--后台入口-->
<span class="nav-item">
  <a class="nav-link" href="/@manage" target="_blank">
    <i class="fa-solid fa-folder-gear" style="color:#409EFF;" aria-hidden="true">
    </i>
    管理
    <!--一言API-->
    <script src="https://v1.hitokoto.cn/?encode=js&select=%23hitokoto" defer></script>
    <script type="text/javascript">
      ! function (e, t, a) { function r() { for (var e = 0; e < s.length; e++) s[e].alpha <= 0 ? (t.body.removeChild(s[e].el), s.splice(e, 1)) : (s[e].y--, s[e].scale += .004, s[e].alpha -= .013, s[e].el.style.cssText = "left:" + s[e].x + "px;top:" + s[e].y + "px;opacity:" + s[e].alpha + ";transform:scale(" + s[e].scale + "," + s[e].scale + ") rotate(45deg);background:" + s[e].color + ";z-index:99999"); requestAnimationFrame(r) } function n() { var t = "function" == typeof e.onclick && e.onclick; e.onclick = function (e) { t && t(), o(e) } } function o(e) { var a = t.createElement("div"); a.className = "heart", s.push({ el: a, x: e.clientX - 5, y: e.clientY - 5, scale: 1, alpha: 1, color: c() }), t.body.appendChild(a) } function i(e) { var a = t.createElement("style"); a.type = "text/css"; try { a.appendChild(t.createTextNode(e)) } catch (t) { a.styleSheet.cssText = e } t.getElementsByTagName("head")[0].appendChild(a) } function c() { return "rgb(" + ~~(255 * Math.random()) + "," + ~~(255 * Math.random()) + "," + ~~(255 * Math.random()) + ")" } var s = []; e.requestAnimationFrame = e.requestAnimationFrame || e.webkitRequestAnimationFrame || e.mozRequestAnimationFrame || e.oRequestAnimationFrame || e.msRequestAnimationFrame || function (e) { setTimeout(e, 1e3 / 60) }, i(".heart{width: 10px;height: 10px;position: fixed;background: #f00;transform: rotate(45deg);-webkit-transform: rotate(45deg);-moz-transform: rotate(45deg);}.heart:after,.heart:before{content: '';width: inherit;height: inherit;background: inherit;border-radius: 50%;-webkit-border-radius: 50%;-moz-border-radius: 50%;position: fixed;}.heart:after{top: -5px;}.heart:before{left: -5px;}"), n(), r() }(window, document); 
    </script>
  </a>
</span>
```

![api](https://github.com/soulteary/docker-flare/assets/47911535/8183714e-e1bf-47fe-878d-e7c04ddfd626)

无论首页还是后台每次刷新网页时 API 请求看起来都是正常的，响应内容也可以正常变化呀。

**Comment by wanrenbuwanxin** [comment]
[代码.txt](https://github.com/soulteary/docker-flare/files/13753856/default.txt)
已文件形式发你了。
https://flare.wscsmile.cn:8888    这个是站点实例，大佬帮忙看看

**Comment by wanrenbuwanxin** [comment]
https://flare.wscsmile.cn:8888/settings/application
后台

**Comment by LightAPIs** [comment]
> [代码.txt](https://github.com/soulteary/docker-flare/files/13753856/default.txt) 已文件形式发你了。 

你没有为 flare [禁用 CSP](https://github.com/soulteary/docker-flare/blob/main/docs/advanced-startup.md#自定义启动参数)。你可以设置环境变量 `FLARE_DISABLE_CSP` 值为 `true` 或者使用启动命令 `-c`。

**Comment by wanrenbuwanxin** [comment]
谢谢大佬，已经弄好了
