### ISSUE TITLE
【单文件版本取消了？】

### ISSUE THREAD

**Issue by Whichbfj28** [soulteary/docker-flare#164]
### 你遇到了什么样的麻烦？

之前有单文件版本的。现在只有docker版本了？

### 如何复现这个问题？

之前有单文件版本的。现在只有docker版本了？

### 应用版本

0.5.1

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by soulteary** [comment]
https://github.com/soulteary/flare/releases/
