### ISSUE TITLE
【应用】、【标签】标题英文由用户自己决定大小写，而不是统一大写

### ISSUE THREAD

**Issue by 6126b70e02c34ea49d855cac8f6af6c3** [soulteary/docker-flare#167]
### 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？

.

### 请描述你想要得到的结果

.

### 请描述你想要的替代方案

.

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by dragonish** [comment]
Duplicate of #127
