### ISSUE TITLE
问题：图标使用

### ISSUE THREAD

**Issue by zsbai** [soulteary/docker-flare#17]
我在https://materialdesignicons.com/ 中找的很多图标都是无法显示的，未来希望可以支持更多，或者支持图片外链

**Comment by soulteary** [comment]
你好👋，我猜测这里是因为直接使用 MDI 的官方带有连字符的图标名称。

关于图标名称使用，可以参考这个文档：

https://github.com/soulteary/docker-flare/blob/main/docs/material-design-icons.md

接下来的版本会支持外链，以及会做一些额外的调整，相关讨论 https://github.com/soulteary/docker-flare/issues/14

**Comment by zsbai** [comment]
十分感谢～之前确实没有注意到连字符的问题

**Comment by soulteary** [comment]
> 十分感谢～之前确实没有注意到连字符的问题

不客气，MDI 不同语言的图标使用方式不同，确实有一些细节。

可以试试使用 /icons + 点击复制，避免输入，可以规避不少问题。 @zsbai

**Comment by zsbai** [comment]
> > 十分感谢～之前确实没有注意到连字符的问题
> 
> 不客气，MDI 不同语言的图标使用方式不同，确实有一些细节。
> 
> 可以试试使用 /icons + 点击复制，避免输入，可以规避不少问题。 @zsbai

了解了～对这个网站还不太熟悉

**Comment by shizunge** [comment]
It would be nice to support icon name with "-" from MDI without modification of the name.
