### ISSUE TITLE
不能直接在页面添加链接吗？还是只能通过编辑配置文件来添加？

### ISSUE THREAD

**Issue by cheng2004237** [soulteary/docker-flare#2]

**Comment by soulteary** [comment]
目前只能通过编辑配置文件来完成，原因在文章中有提及 :)

https://soulteary.com/2022/02/08/building-bookmark-navigation-for-homelab-with-docker.html#%E5%9C%A8%E5%AE%B9%E5%99%A8%E4%B8%AD%E4%BD%BF%E7%94%A8-flare

**Comment by soulteary** [comment]
在线编辑器，第一个版本已经发布。

https://github.com/soulteary/docker-flare/issues/11
