### ISSUE TITLE
功能：隐藏设置图标

### ISSUE THREAD

**Issue by fgprodigal** [soulteary/docker-flare#20]
我想部署成公司内部的网址导航，不想让别人在网页界面上随意修改配置，建议在config.yaml里加个隐藏设置按钮的功能

**Comment by soulteary** [comment]
你好👋，可以在启动时，指定启动参数，启用程序用户登陆功能。

```bash
docker run --rm -it -p 5005:5005 -v `pwd`/app:/app soulteary/flare:0.2.9-amd64 flare --nologin=0
```

或者设置环境变量 `FLARE_DISABLE_LOGIN=0` 即可。 @fgprodigal

**Comment by soulteary** [comment]
原本关闭了 issue，想了下如果后台有这么一个配置，那么界面可以更简洁，下个版本中我更新一下。谢谢建议 @fgprodigal

**Comment by soulteary** [comment]
可以在设置->界面中找到对应的设置项，将元素隐藏。 @fgprodigal 

![image](https://user-images.githubusercontent.com/1500781/155254439-b4ac56c1-2789-40d4-ae01-a67500b047c2.png)
