### ISSUE TITLE
建议 是否可以将主页设置为登陆后才能访问

### ISSUE THREAD

**Issue by OTritium** [soulteary/docker-flare#23]
部分服务器后台页面不希望在公网自由访问

**Comment by soulteary** [comment]
谢谢反馈，这倒也是个使用场景。在此之前可以试试 traefik + basic auth 或者 traefik + forward auth，我之前的文章中有提到过。

我会将这个需求添加到发布列表里，接下来的最近两个版本发布掉。

**Comment by soulteary** [comment]
可以参考这里。 @OTritium 


https://github.com/soulteary/docker-flare/tree/main/example/private
