### ISSUE TITLE
图标界面增加搜索

### ISSUE THREAD

**Issue by OTritium** [soulteary/docker-flare#29]
图标太多找起来太麻烦了……可否增加名称搜索

**Comment by pharder56k** [comment]
> 图标太多找起来太麻烦了……可否增加名称搜索

直接ctrl+f 调出浏览器搜索就行了

**Comment by soulteary** [comment]
嗯，这里如果要做搜索，首先需要做的是针对图标的分类，甚至是汉化，所以单纯做搜索，可能意义不大。

相比之下，确实是 @pharder56k 提到的，使用 ctrl+f 更为直接一些。

不过或许可以看看有没有地方能够找到“高频使用”的 MDI 图标数据，做一个额外的置顶展示。

感谢反馈 @OTritium
