### ISSUE TITLE
将chrome扩展地址保存为application后出错

### ISSUE THREAD

**Issue by ember-zhang** [soulteary/docker-flare#3]
Hi,
chrome扩展地址可以正常保存，但主页内的链接中，其冒号会消失：
类似chrome-extension://abcdefg 这样的地址，创建、编辑application时显示都正常；
但在主页显示为 chrome-extension//abcdefg ，丢失冒号，导致无法打开

**Comment by soulteary** [comment]
你好👋， @ember-zhang 

我使用 `0.2.3` 测试之后没有复现，我猜测应该和浏览器客户端版本有关。为了一劳永逸的解决这个问题，我更新了一个小版本，将 `chrome-extension://` 协议开头的链接，交给 flare 接口进行跳转处理，替换了原本在浏览器页面中使用 HTML 进行跳转的方式。

你可以试试 `0.2.4` 版本，或许会对你有帮助。

此外，因为 chrome 安全策略的缘故，使用服务器进行重定向打开的浏览器插件页面，需要用户手动“刷新”，才能触发页面渲染。

ps: 你的 id 很熟悉，像一位老朋友 :)

**Comment by ember-zhang** [comment]
你好，
感谢响应！0.2.4版本正常使用，如您所说的，由于chrome策略的缘故确实也需要手动刷新^_^
