### ISSUE TITLE
建议:  希望应用里字母大小写与配置文件保持一致

### ISSUE THREAD

**Issue by llussy** [soulteary/docker-flare#31]
目前应用里字母都是大写。
![image](https://user-images.githubusercontent.com/18432966/156317838-7915015e-af96-4b86-9b36-ba9f4b938ac6.png)
![image](https://user-images.githubusercontent.com/18432966/156317875-f6d412f3-576e-467d-bb24-3ab0a2989ceb.png)

**Comment by kscu** [comment]
> 目前应用里字母都是大写。 ![image](https://user-images.githubusercontent.com/18432966/156317838-7915015e-af96-4b86-9b36-ba9f4b938ac6.png) ![image](https://user-images.githubusercontent.com/18432966/156317875-f6d412f3-576e-467d-bb24-3ab0a2989ceb.png)

支持

**Comment by soulteary** [comment]
@llussy @kscu 感谢反馈，这里应该增加一个界面选项，允许调整展示的内容是大写或者和配置保持一致。

**Comment by soulteary** [comment]
已解决，可以试试 0.3.3 版本 @llussy @kscu 

https://github.com/soulteary/docker-flare/releases/tag/v0.3.3
