### ISSUE TITLE
建议：希望不登录可以隐藏一些书签

### ISSUE THREAD

**Issue by xsun12131** [soulteary/docker-flare#34]

**Comment by cqboyone** [comment]
同问，不想把应用和书签暴露出去。能增加登录了才能看到书签和应用的功能吗？

**Comment by soulteary** [comment]
@cqboyone @xsun12131 目前支持登陆后才能浏览书签，可以参考 https://github.com/soulteary/docker-flare/tree/main/example/private 中的例子。
