### ISSUE TITLE
帮助页面莫名就空白了

### ISSUE THREAD

**Issue by harrison-guo-chn** [soulteary/docker-flare#39]
![image](https://user-images.githubusercontent.com/58265745/156892194-c71d4751-0713-41cd-84fc-a6d786233368.png)
如图

**Comment by harrison-guo-chn** [comment]
已经找到原因，设置-界面-展示应用模块-否 就会这样

**Comment by harrison-guo-chn** [comment]
> ![image](https://user-images.githubusercontent.com/58265745/156892194-c71d4751-0713-41cd-84fc-a6d786233368.png) 如图

**Comment by soulteary** [comment]
@harrison-guo-chn 感谢反馈，我明天排查一下。

**Comment by soulteary** [comment]
已解决，可以试试 0.3.3 版本 @harrison-guo-chn 

https://github.com/soulteary/docker-flare/releases/tag/v0.3.3
