### ISSUE TITLE
建议：HTML设置为中文语言

### ISSUE THREAD

**Issue by shuax** [soulteary/docker-flare#41]
现在是en，浏览器会自动弹翻译框。
![image](https://user-images.githubusercontent.com/6940583/156924257-fbb7bbf0-df13-4da8-9f08-f9f56fa9f1fa.png)

**Comment by soulteary** [comment]
感谢反馈，最近的新版本会做修正。 @shuax

**Comment by soulteary** [comment]
已解决，可以试试 0.3.3 版本。 @shuax 

https://github.com/soulteary/docker-flare/releases/tag/v0.3.3

**Comment by shuax** [comment]
notranslate ok

**Comment by soulteary** [comment]
> notranslate ok

👌，这里有一个小细节，如果我们直接修改目标页面内容的“语言”的话，英文操作系统的同学还是会蹦出来提示框，所以，我换了一个实现方案，感兴趣的话，可以挖掘下。 :D @shuax
