### ISSUE TITLE
反馈：关闭标题组件时无法显示日期

### ISSUE THREAD

**Issue by shuax** [soulteary/docker-flare#44]
设置如图
![image](https://user-images.githubusercontent.com/6940583/157623688-66a8f806-4cd6-4e3a-8373-f230cb20e5ca.png)

**Comment by soulteary** [comment]
感谢反馈，确实是个问题（这里和模版实现有关系）。 @shuax 

我试试看下一个版本能不能把模版相关功能代码整理完毕。优先完成这块的代码开源，以及自定义模版功能，这样大家就能自己玩了...

**Comment by soulteary** [comment]
已修复，将于下个版本中发布 :D

模版功能考虑拆分一个工具来实现，这样可以避免应用体积变大，以及降低模版构建的难度。

**Comment by soulteary** [comment]
新版本已发布，可以试试看 :D  @shuax 

https://github.com/soulteary/docker-flare/releases/tag/v0.4.0 

```bash
docker pull soulteary/flare
# 或者
docker pull soulteary/flare:0.4.0
```

然后更新 `docker-compose.yml` 中的版本号即可。
