### ISSUE TITLE
建议：将免密码登录设置为环境变量，而非启动的参数。

### ISSUE THREAD

**Issue by flashliao** [soulteary/docker-flare#5]
建议：将免密码登录设置为环境变量，而非启动的参数。
最主要是我的Docker是在群晖里面运行的。只能改变环境变量，改变不了启动参数。或者用更加复杂的方法。建议设置为environment:可以更改的参数。

**Comment by soulteary** [comment]
感谢建议，后面的版本会考虑添加更多环境变量来解决问题。

解释一下为何当前这样设计，我希望区分可变和不变两种状态，相比较环境变量可能会被其他的程序变更（比如拥有 docker daemon 权限），启动命令更为“固定”，不过在你提到的场景下，变通也不是不可。

如果你希望现在就能够使用的话，可以考虑使用 `docker-compose` 的方式来运行软件，群晖是支持的。

**Comment by soulteary** [comment]
周末重构了代码，目前所有的命令行参数均可使用环境变量替换，文档稍后更新。 @flashliao 

需要使用新版本：https://github.com/soulteary/docker-flare/releases/tag/v0.2.9

**Comment by soulteary** [comment]
https://github.com/soulteary/docker-flare/blob/main/docs/advanced-startup.md

可用环境变量列表已更新。
