### ISSUE TITLE
希望可以有设置导航标签只能登录可见的功能

### ISSUE THREAD

**Issue by pegasusknightyf** [soulteary/docker-flare#57]
因为要在公网上进行访问，现在这样有隐私性问题。希望可以设置标签登录可见等权限

另外要是有多用户管理，不同用户可以有自己不同的导航内容就更好了

**Comment by pegasusknightyf** [comment]
不好意思，之前没找到这个功能，现在找到了

**Comment by chenweiask** [comment]
> 不好意思，之前没找到这个功能，现在找到了

我的理解，你提的要求是不同用户访问可以看到不同的书签。是这样吗？
能请问一下你是怎么实现的吗？
