### ISSUE TITLE
外网ipv6访问失败

### ISSUE THREAD

**Issue by Linyue-GitHub** [soulteary/docker-flare#59]
通过docker部署的  ipv4访问可以 ipv6访问显示拒绝连接

**Comment by sungamma** [comment]
可以试试npm反向代理，还能加锁

**Comment by quark-mac** [comment]
> 通过docker部署的 ipv4访问可以 ipv6访问显示拒绝连接

看一下有没有防火墙，或者容器网络设置是否正确
