### ISSUE TITLE
建议：优化关于移动端适配问题

### ISSUE THREAD

**Issue by flashliao** [soulteary/docker-flare#6]
移动端是适配的，但是我发现我用的是小米9，能够显示一排4个应用。但是标题和描述仅能显示2个字左右。超过2个或3个将会用...不显示。建议优化 建议移动端考虑。能够一排仅显示3个应用 或者优化排版布局。例如占据更高？ 显示更多的字。

**Comment by soulteary** [comment]
谢谢提醒。

坦白说，HomeLab 场景下更高频是使用桌面设备，所以移动端确实没有更多的考虑。

这个调整需要在主要功能都完全稳定之后再做了，我更希望相比较当前的模式，能够让大家自己定义 模版，自己定义 主题配色，而不光是开箱即用。

**Comment by soulteary** [comment]
Hi, 我试着更新了一个小版本，先做了一点简单的适配，可以试试看。

更好的状态，应该还是得等整体稳定后再做了。 @flashliao 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/1500781/154616362-a4329b14-e14d-41b1-a278-d879e3494786.png">
