### ISSUE TITLE
反馈：无法登录问题

### ISSUE THREAD

**Issue by hzmabin** [soulteary/docker-flare#68]
### 你遇到了什么样的麻烦？

在初始化时设置了用户和密码，之前登录修改页面和配置也正常，最近页面使用都正常，想修改下配置但发现无法登录了。
在确认正确填写用户名和密码之后提示：

用户名或密码不能为空 [返回重试](http://192.168.*.*:5005/settings/application)

或前往 https://github.com/soulteary/docker-flare/issues/ 反馈使用中的问题，谢谢！

注：尝试重新启动docker应用和更换其他浏览器还是无法解决。

### 应用版本

soulteary/flare:0.3.1

### 搜索

- [x] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by lhuanyun** [comment]
同样的，一段时间后出现了这个问题。0.3.3

**Comment by soulteary** [comment]
@hzmabin @xiaohai2020 感谢反馈。最近将发布新版本，解决这个问题。（计划版本号 0.4.0）

**Comment by soulteary** [comment]
新版本已发布，可以试试看 :D @hzmabin @xiaohai2020 

https://github.com/soulteary/docker-flare/releases/tag/v0.4.0 

```bash
docker pull soulteary/flare
# 或者
docker pull soulteary/flare:0.4.0
```

然后更新 `docker-compose.yml` 中的版本号即可。

**Comment by koromon** [comment]
请问下问什么我按照这个配置还是提示账号/密码不能为空呢。

<img width="502" alt="image" src="https://user-images.githubusercontent.com/13466007/193398885-c131e4d5-2482-4376-9ce2-d63d11f6fee4.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/13466007/193398880-5bdc4e95-6ecf-4bab-ac2b-5d82a706ad24.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/13466007/193398911-5533ffff-d6d4-4b95-8d76-79270b80bda2.png">

**Comment by koromon** [comment]
> https://github.com/soulteary/docker-flare/blob/main/example/private/docker-compose.yml @koromon 使用的是这个配置嘛？

欸，我今天试了下又可以了。。。抱歉，应该是我之前哪里配置错了。非常感谢

**Comment by soulteary** [comment]
没事儿，有可能是运行的还是老镜像... @koromon docker pull pull 更健康，:D
