### ISSUE TITLE
Bug: 设置选项回显

### ISSUE THREAD

**Issue by viticis** [soulteary/docker-flare#7]
> 版本: 0.2.6

1. 设置中每个下拉框选项都变成了4个：`是、否、是、否`
2. 设置中的下拉框选项无法回显，默认都显示 `否` ，无法得知当前设置项

**Comment by soulteary** [comment]
https://github.com/soulteary/docker-flare/releases/tag/v0.2.7 @viticis 已修复。

**Comment by viticis** [comment]
> https://github.com/soulteary/docker-flare/releases/tag/v0.2.7 @viticis 已修复。

感谢，另建议docker hub同时上传laster的tag，release时候同时更新一下laster，用户使用时候不必加版本号，更新也可以直接pull.

**Comment by soulteary** [comment]
已添加，感谢建议。 @viticis 

https://github.com/soulteary/docker-flare/issues/8
