### ISSUE TITLE
关闭显示设置与帮助后，但是在应用及书签页还是会显示出来的。

### ISSUE THREAD

**Issue by liushuaiiu** [soulteary/docker-flare#70]
### 你遇到了什么样的麻烦？

![image](https://user-images.githubusercontent.com/42984729/178198911-b4d372bf-2024-4a1d-9b3b-dbf80b31f5ee.png)
关闭显示【设置】与【帮助】后，但是在应用及书签页还是会显示出来的。

### 如何复现这个问题？

关闭显示【设置】与【帮助】后，但是在应用及书签页还是会显示出来的。

### 应用版本

最新版

### 搜索

- [ ] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by soulteary** [comment]
谢谢反馈。

应该是老版本程序的问题，可以先试试 0.3.3 版本。或者等待接下来发布的 0.4.0 版本。 @liushuaiiu

**Comment by liushuaiiu** [comment]
是的，是用的就是0.3.3。
[image0.jpeg]

发自我的 iPhone

在 2022年9月17日，19:01，Su Yang ***@***.***> 写道：

﻿

谢谢反馈。

应该是老版本程序的问题，可以先试试 0.3.3 版本。或者等待接下来发布的 0.4.0 版本。 @liushuaiiu<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliushuaiiu&data=05%7C01%7C%7Cb8d0b096a9cb4f15c5dc08da989bfda9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637990093018872099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G7hyhCssqNu3immnEmfIJvfyBhBr1QrRx771Ym9HhUI%3D&reserved=0>

**Comment by soulteary** [comment]
@liushuaiiu 可以切换到 0.4.0 试试

**Comment by soulteary** [comment]
thanks @LightAPIs

**Comment by soulteary** [comment]
更新： v0.4.1 发布
