### ISSUE TITLE
反馈：无法加载统计代码

### ISSUE THREAD

**Issue by onmpen** [soulteary/docker-flare#72]
### 你遇到了什么样的麻烦？

似乎是由于CSP策略导致无法加载 js 统计脚本

### 如何复现这个问题？

在界面设置页脚部分添加谷歌统计代码后，刷新后提示：

Refused to load the script 'https://https://www.googletagmanager.com/gtag/js?id=ccccc.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

### 应用版本

docker flare:latest

### 搜索

- [ ] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

### 补充描述

请问要怎样设置才能加载统计代码？

**Comment by soulteary** [comment]
我添加了一个新的 FLAG，用来按需禁用 CSP，让统计代码可以正常加载，应该可以解决你的问题。

你可以通过 cli 参数 `disable_csp=1` 或者 环境变量 `FLARE_DISABLE_CSP=0` 来解决问题。

新版本预期在周一前发布 :D @onmpen

**Comment by soulteary** [comment]
新版本已发布，可以试试看 :D  @onmpen 

https://github.com/soulteary/docker-flare/releases/tag/v0.4.0 

```bash
docker pull soulteary/flare
# 或者
docker pull soulteary/flare:0.4.0
```

然后更新 `docker-compose.yml` 中的版本号即可。
