### ISSUE TITLE
只能有4个分类吗？

### ISSUE THREAD

**Issue by xh542428798** [soulteary/docker-flare#74]
### 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？

只能有4个分类吗？

### 请描述你想要得到的结果

只能有4个分类吗？

### 请描述你想要的替代方案

想要多一点分类

### 搜索

- [ ] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by JKnuts** [comment]
![image](https://user-images.githubusercontent.com/91355283/190501065-b6fac452-e76d-4434-bb49-124d47506d19.png)
右键有惊喜

**Comment by soulteary** [comment]
@JKnuts 谢谢解答。

@xh542428798 造成这个问题的原因除了文档和需要重构的编辑工具外，和当前模版结构也有关系，后续将考虑增加一个小功能：https://github.com/soulteary/docker-flare/issues/78

**Comment by thelittlefox** [comment]
> @JKnuts 谢谢解答。
> 
> @xh542428798 造成这个问题的原因除了文档和需要重构的编辑工具外，和当前模版结构也有关系，后续将考虑增加一个小功能：#78

建议当前在editor页面最上面的提示中增加一行关于如何添加分类的提示。
对4个分类的这个问题困惑了好一会儿。
