### ISSUE TITLE
首页密码登陆的页面不显示自定义页脚

### ISSUE THREAD

**Issue by 404gods** [soulteary/docker-flare#77]
### 你遇到了什么样的麻烦？

首页密码登陆的页面不显示自定义页脚，这样就不显示ICP备案信息，就会被biubiu
![网页捕获_15-9-2022](https://user-images.githubusercontent.com/50573302/190302373-16b9b848-c16b-49be-b097-9a08961d1c36.jpeg)

### 如何复现这个问题？

首页密码登陆的页面不显示自定义页脚

### 应用版本

0.3.3 / fe6d1f4

### 搜索

- [ ] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by soulteary** [comment]
@404gods 感谢反馈，已经修正，新版本中不会出现这个问题啦  :D

**Comment by soulteary** [comment]
新版本已发布，可以试试看 :D  @404gods 

https://github.com/soulteary/docker-flare/releases/tag/v0.4.0 

```bash
docker pull soulteary/flare
# 或者
docker pull soulteary/flare:0.4.0
```

然后更新 `docker-compose.yml` 中的版本号即可。
