### ISSUE TITLE
建议：建议 Docker hub 镜像推送 latest 标签，方便 Pull

### ISSUE THREAD

**Issue by eallion** [soulteary/docker-flare#8]
建议 Docker hub 镜像推送 latest 标签，方便 Pull。

**Comment by eallion** [comment]
在测试这个了，看起来还不错，可能会切换过来。

**Comment by soulteary** [comment]
我试着推送了一个版本，可以试试看。（如果有缓存问题，可以跟帖反馈，谢谢 @eallion 

<img width="841" alt="image" src="https://user-images.githubusercontent.com/1500781/154616218-ddf7fce6-2ba6-47f2-a339-fa5b1a2d384f.png">

**Comment by eallion** [comment]
可以 Pull latest 版本。
docker-compose.yml 配置文件也可以改为 latest 版本，这样就不用每次发版都要修改一次。

**Comment by soulteary** [comment]
@eallion 已全部更新，谢谢提醒。
