### ISSUE TITLE
没有dockerfile文件吗

### ISSUE THREAD

**Issue by JossSong** [soulteary/docker-flare#82]
### 请描述你为什么要申请这个功能，是在使用的过程中遇到了什么问题嘛？

尝试用railway部署flare,默认只识别根目录dockerfile文件

### 请描述你想要得到的结果

自己构建了一下，但是希望官仓能提供dockerfile文件

### 请描述你想要的替代方案

自己构建了一下，但是希望官仓能提供dockerfile文件

### 搜索

- [ ] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by soulteary** [comment]
https://github.com/soulteary/docker-flare/issues/4 @JossSong 代码在这里，提供了 dockerfile，以及更透明的基于 GitHub Action 构建的 workflow :D
