### ISSUE TITLE
天气数据获取失败

### ISSUE THREAD

**Issue by he-sb** [soulteary/docker-flare#89]
### 你遇到了什么样的麻烦？

首页无法展示天气，在设置中测试时返回

```bash
获取远程数据失败
```

![图片](https://user-images.githubusercontent.com/26474615/201506545-dcca735f-ddb2-4cf3-9bb3-9153a799cee9.png)

### 如何复现这个问题？

通过项目源码看到天气数据是通过 `https://wis.qq.com/weather/common?source=pc&weather_type=observe&province="+province+"&city="+city` 获取的，尝试直接调用此接口，发现浏览器提示该域名证书在两天前过期了，不知到是否是这个原因导致的：

![图片](https://user-images.githubusercontent.com/26474615/201506698-07d4038d-60db-45ff-bc37-e8c1fcac3910.png)

### 应用版本

`0.4.0 / 9d209e38a3bc7637e14e0762efc7e4bc8f39d03e`

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by he-sb** [comment]
疼讯天气更新了证书，现在没问题了。。

**Comment by iizx** [comment]
> 

我的仍然获取不到天气

**Comment by he-sb** [comment]
@iizx 尝试使用隐身模式，或者更换浏览器，如果不能复现问题，应该是浏览器缓存的问题，清空一下再试试
